### ISSUE TITLE
PostLog stopped short writing logs to remote server

### ISSUE THREAD

**Issue by johnxjcheng** [statianzo/PostLog#3]
I am trying to use PostLog and facing an issue that it won’t post more than 2 logs across intranet. However when testing against a locally hosted receiver, all posts went through. I checked with Wireshark log. I can confirm that the post only happened twice. I also obtained the latest source code of PostLog, and placed some tracing code to see the behavior. Here is the code I traced:

       protected override void Append(LoggingEvent loggingEvent)
        {
            System.Diagnostics.Trace.WriteLine(">>> Append");

            byte[] bodyBytes;

            try
            {
                string body = BodyFormatter.CreateBody(loggingEvent, _parameters);
                bodyBytes = Encoding.UTF8.GetBytes(body);
            }
            catch (Exception e)
            {
                ErrorHandler.Error("Failed to create body", e);
                return;
            }

            HttpWebRequest request = BuildRequest();

            request.BeginGetRequestStream(r =>
                {

                    try
                    {
                        System.Diagnostics.Trace.WriteLine(">>> BeginWrite");
                        Stream stream = request.EndGetRequestStream(r);
                        stream.BeginWrite(bodyBytes, 0, bodyBytes.Length, c =>
                            {
                                try
                                {
                                    stream.Dispose();
                                    System.Diagnostics.Trace.WriteLine(">>> BeginGetResponse");
                                    request.BeginGetResponse(a =>
                                        {
                                            try
                                            {
                                                System.Diagnostics.Trace.WriteLine(">>> BeginGetResponse");
                                                request.EndGetResponse(a);
                                            }
                                            catch (Exception e)
                                            {
                                                ErrorHandler.Error("Failed to get response", e);
                                            }
                                        }, null);
                                    System.Diagnostics.Trace.WriteLine(">>> EndWrite");
                                    stream.EndWrite(c);
                                }
                                catch (Exception e)
                                {
                                    ErrorHandler.Error("Failed to write", e);
                                }
                            }, null);

                    }
                    catch (Exception e)
                    {

                        ErrorHandler.Error("Failed to connect", e);
                    }
                }, null);
        }

And here is the log I got: 

[11904] log4net: Hierarchy Threshold [] 
[11904] >>> Append 
[11904] >>> Append 
[11904] >>> BeginWrite 
[11904] >>> BeginGetResponse 
[11904] >>> Append 
[11904] >>> Append 
[11904] >>> EndWrite 
[11904] >>> BeginWrite 
[11904] >>> BeginGetResponse 
[11904] >>> EndWrite 
[11904] >>> Append 
[11904] >>> Append 
[11904] >>> Append 
[11904] >>> BeginGetResponse 
[11904] >>> BeginGetResponse 
[11904] log4net: Shutdown called on Hierarchy [log4net-default-repository] 

The 7 'Append' corresponds to my 7 calls I had to Log. Now you can see the 'BeginWrite' only happen twice.

**Comment by statianzo** [comment]
Closed by #4
